### ISSUE TITLE
Re-add features that were removed, they have already been abandoned and issues not fixed.

### ISSUE THREAD

**Issue by TomLewis** [eirikh1996/Movecraft#120]
**Describe the bug**
When the features of Movecraft were removed like Cannon support, Crew signs, WorldGaurd support in favour of having them their own plugins, I said this would be a bad idea as now getting bugs fixed is reliant on the third-party developer.
Well the day it went live I tested it and found bugs with "Beaming" in **May** were now in July and the issues have not even been looked at.

https://github.com/APDevTeam/Beaming/issues

This is just 1 of the features, I only needed crew signs back from that plugin, I didn't even get around to testing the WG & cannon extra plugins to see how they changed how they work.

I have seen this happen before with multiple plugins, every time they make "addons" run by third parties the third parties NEVER update or fix anything.

I suggest having all "addons" under 1 plugin, like WorldGuardExtras does, and it's run by an active developer.
Then we can request third party additions to that one Repo, Like right now I need GriefPrevetion bug fixed with /manoverboard but I cant request it here because that would be classed as "not part of Movecraft" as its a third party plugin support, I cant request it to any of the many "addon" developers as they are already inactive and don't fix bugs!

Please combine all of the "addons" to a repo/plugin called something like MoveCraftExtras (Like WGExtras) where we can report/request third party integration.

**Comment by TomLewis** [comment]
1. Bug 1 https://github.com/APDevTeam/Beaming/issues/5
2. Bug 2 https://github.com/APDevTeam/Beaming/issues/6

Killing a player for using it, it also hangs in issue 6 and ALSO gives an error message in chat, so that's like 3 Bugs in 1 Issue I've reported.

I still have not been able to update to the latest Movecraft because of the bugs present in other repos that have not even been looked at.  Previously I could just update Movecraft, now I can't.

**Comment by cccm5** [comment]
> Killing a player for using it!!!??? How is that not a bug?

Killing the player with `/beam` is the intended feature of the plugin. It's just a `/suicide`.

> it also hangs in issue 6 and ALSO gives an error message in chat, so that's like 3 Bugs in 1 Issue I've reported.

 The error you're getting after death message I have no idea if that's even an issue with the plugin or not (it almost looks like an essentials error if I was to speculate). I am not the maintainer of beaming, but the title on the issue doesn't indicate that the problem you're having is anything other than a feature request. I should have read it in more depth before responding however.
 
> I still have not been able to update to the latest Movecraft because of the bugs present in other repos that have not even been looked at. Previously I could just update Movecraft, now I can't.
> I reported them, in May in those repos, you have replied the SAME day in this repo!

I do not maintain the add-ons, Both the person who does and I work a full time job. The reality is that we work when we can, and we do so for free. We get to things when we can.

**Comment by TylerS1066** [comment]
> Well the day it went live I tested it and found bugs with "Beaming" in **May** were now in July and the issues have not even been looked at.

By default the plugin comes configured to directly replace the features removed from Movecraft (namely `Crew:` signs).  The additional features of `/beam` require that you give your players the `beaming.beam` permission or enable them in the config.  You stated that "I only needed crew signs back from that plugin" and by default Beaming comes prepared to do this.

My goal with the initial releases of the addons was to include at a minimum the features from the main plugin, and possibly more (like Movecraft-Combat).  Your requested features were changes to the additional functionality, and so I put it at a lower priority than upgrading my testing server to 1.14.4 and fixing the problems in Movecraft-Cannons 1.14.4 (https://github.com/TylerS1066/Movecraft-Cannons/issues/9).

> This is just 1 of the features, , I didn't even get around to testing the WG & cannon extra plugins to see how they changed how they work.

Movecraft-Worldguard is working great for us on our servers running 1.12.2, and is functioning well on our 1.14.4 test server as well.  Movecraft-Cannons functions well on 1.12.2, but seems to be hit or miss on 8.0/1.14.4+.  I'm currently focusing on gathering information from the various servers that have had problems, but I know of about half of the servers are using it with no problems.  Regardless, once my 1.14.4 testing server is fully set up I'll be focusing my attention on this.

> I have seen this happen before with multiple plugins, every time they make "addons" run by third parties the third parties NEVER update or fix anything.

I'm not a third party, I'm the owner of the Airship Pirates server.  The Airship Pirates Dev Team, who have maintained Movecraft since 2017, are the development branch of our staff team.  I fully admit that the Cannons addon and features like you requested are not as high of a priority for me as the rest of the addons since they are not what my server uses, but I still try to work on them.  Unfortunately, as cccm5 pointed out, both she and I have full time jobs and do this as a hobby, so we have to prioritize our time on critical issues before adding new features.

> not even been looked at

I apologize for not replying to your feature requests, but I did read them the day you posted them.  I didn't reply to them yet because they are feature requests, which I put at a lower priority than the *many* bugs I am currently working on.  I fully admit to missing the message about the data not found error, but I'll open up a bug report for it where we can dig more into the problem.

**Comment by TomLewis** [comment]
@TylerS1066 Thank you so much for the update! Sorry I was getting aggravated with being stuck.
That's nice to know you are the owner now, I still thought it was BaccaYarro!

I was just getting reports of issues from players and not sure how/where to report them when it's related to third party plugins (GriefPrevention) and with the recent separation of extra features into their own individual repos, it leaves no place to request support for other issues (GriefPrevention).
I still think having all `MoveCraftExtras` in one plugin/repo would be much neater with keeping jars updated, but also for adding additional extra support for other plugins! I have so many ideas for integration with other plugins!
This means this could be 1 spigot page instead of multiple too, and just list features for the extras it adds.

I would honestly love to use the /beam feature and re-brand it, so if it can be repaired that would be amazing.
